//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.2.0
//     from Assets/Johnny Early Protos/Environment.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Environment : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Environment()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Environment"",
    ""maps"": [
        {
            ""name"": ""Interactions"",
            ""id"": ""2f2f0864-9f37-46a7-ab89-4e7f399d3ed0"",
            ""actions"": [
                {
                    ""name"": ""Peek"",
                    ""type"": ""Button"",
                    ""id"": ""f0b3c8ef-1a75-4f10-8317-2fa38fed59b5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""476f0cac-4be0-47b5-9712-7d042acb6c98"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Peek"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Interactions
        m_Interactions = asset.FindActionMap("Interactions", throwIfNotFound: true);
        m_Interactions_Peek = m_Interactions.FindAction("Peek", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Interactions
    private readonly InputActionMap m_Interactions;
    private IInteractionsActions m_InteractionsActionsCallbackInterface;
    private readonly InputAction m_Interactions_Peek;
    public struct InteractionsActions
    {
        private @Environment m_Wrapper;
        public InteractionsActions(@Environment wrapper) { m_Wrapper = wrapper; }
        public InputAction @Peek => m_Wrapper.m_Interactions_Peek;
        public InputActionMap Get() { return m_Wrapper.m_Interactions; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InteractionsActions set) { return set.Get(); }
        public void SetCallbacks(IInteractionsActions instance)
        {
            if (m_Wrapper.m_InteractionsActionsCallbackInterface != null)
            {
                @Peek.started -= m_Wrapper.m_InteractionsActionsCallbackInterface.OnPeek;
                @Peek.performed -= m_Wrapper.m_InteractionsActionsCallbackInterface.OnPeek;
                @Peek.canceled -= m_Wrapper.m_InteractionsActionsCallbackInterface.OnPeek;
            }
            m_Wrapper.m_InteractionsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Peek.started += instance.OnPeek;
                @Peek.performed += instance.OnPeek;
                @Peek.canceled += instance.OnPeek;
            }
        }
    }
    public InteractionsActions @Interactions => new InteractionsActions(this);
    public interface IInteractionsActions
    {
        void OnPeek(InputAction.CallbackContext context);
    }
}
